#ifndef __APIO_SENSOR_REGS_H
#define __APIO_SENSOR_REGS_H

#include <io.h> //Altera IOWR and IORD

// Registers address
#define ADDR_RED_THRESHOLD_MIN      0x00
#define ADDR_RED_THRESHOLD_MAX      0x04
#define ADDR_GREEN_THRESHOLD_MIN    0x08
#define ADDR_GREEN_THRESHOLD_MAX    0x0c
#define ADDR_BLUE_THRESHOLD_MIN     0x10
#define ADDR_BLUE_THRESHOLD_MAX     0x14

#define IORD_SENSOR_RED_THRESHOLD_MIN(base)         IORD(base, ADDR_RED_THRESHOLD_MIN)
#define IOWR_SENSOR_RED_THRESHOLD_MIN(base, dat)    IOWR(base, ADDR_RED_THRESHOLD_MIN, dat)
#define IORD_SENSOR_RED_THRESHOLD_MAX(base)         IORD(base, ADDR_RED_THRESHOLD_MAX)
#define IOWR_SENSOR_RED_THRESHOLD_MAX(base, dat)    IOWR(base, ADDR_RED_THRESHOLD_MAX, dat)

#define IORD_SENSOR_GREEN_THRESHOLD_MIN(base)        IORD(base, ADDR_GREEN_THRESHOLD_MIN)
#define IOWR_SENSOR_GREEN_THRESHOLD_MIN(base, dat)   IOWR(base, ADDR_GREEN_THRESHOLD_MIN, dat)
#define IORD_SENSOR_GREEN_THRESHOLD_MAX(base)        IORD(base, ADDR_GREEN_THRESHOLD_MAX)
#define IOWR_SENSOR_GREEN_THRESHOLD_MAX(base, dat)   IOWR(base, ADDR_GREEN_THRESHOLD_MAX, dat)

#define IORD_SENSOR_BLUE_THRESHOLD_MIN(base)         IORD(base, ADDR_BLUE_THRESHOLD_MIN)
#define IOWR_SENSOR_BLUE_THRESHOLD_MIN(base, dat)    IOWR(base, ADDR_BLUE_THRESHOLD_MIN, dat)
#define IORD_SENSOR_BLUE_THRESHOLD_MAX(base)         IORD(base, ADDR_BLUE_THRESHOLD_MAX)
#define IOWR_SENSOR_BLUE_THRESHOLD_MAX(base, dat)    IOWR(base, ADDR_BLUE_THRESHOLD_MAX, dat)

#endif
