# TCL File Generated by Component Editor 10.1sp1
# Thu Sep 15 13:55:54 CEST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | apio_sensor "Sensor" v1.0
# | null 2011.09.15.13:55:54
# | 
# | 
# | C:/Users/Jorge/workspace/VideoSensor/NiosSystem/apio_sensor/hdl/apio_sensor.v
# | 
# |    ./hdl/apio_sensor.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module apio_sensor
# | 
set_module_property NAME apio_sensor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME Sensor
set_module_property TOP_LEVEL_HDL_FILE hdl/apio_sensor.v
set_module_property TOP_LEVEL_HDL_MODULE apio_sensor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/apio_sensor.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter RED_THRESHOLD_MIN STD_LOGIC_VECTOR 424673280
set_parameter_property RED_THRESHOLD_MIN DEFAULT_VALUE 424673280
set_parameter_property RED_THRESHOLD_MIN DISPLAY_NAME RED_THRESHOLD_MIN
set_parameter_property RED_THRESHOLD_MIN TYPE STD_LOGIC_VECTOR
set_parameter_property RED_THRESHOLD_MIN UNITS None
set_parameter_property RED_THRESHOLD_MIN ALLOWED_RANGES 0:17179869183
set_parameter_property RED_THRESHOLD_MIN AFFECTS_GENERATION false
set_parameter_property RED_THRESHOLD_MIN HDL_PARAMETER true
add_parameter RED_THRESHOLD_MAX STD_LOGIC_VECTOR 1073026373
set_parameter_property RED_THRESHOLD_MAX DEFAULT_VALUE 1073026373
set_parameter_property RED_THRESHOLD_MAX DISPLAY_NAME RED_THRESHOLD_MAX
set_parameter_property RED_THRESHOLD_MAX TYPE STD_LOGIC_VECTOR
set_parameter_property RED_THRESHOLD_MAX UNITS None
set_parameter_property RED_THRESHOLD_MAX ALLOWED_RANGES 0:17179869183
set_parameter_property RED_THRESHOLD_MAX AFFECTS_GENERATION false
set_parameter_property RED_THRESHOLD_MAX HDL_PARAMETER true
add_parameter GREEN_THRESHOLD_MIN STD_LOGIC_VECTOR 281600
set_parameter_property GREEN_THRESHOLD_MIN DEFAULT_VALUE 281600
set_parameter_property GREEN_THRESHOLD_MIN DISPLAY_NAME GREEN_THRESHOLD_MIN
set_parameter_property GREEN_THRESHOLD_MIN TYPE STD_LOGIC_VECTOR
set_parameter_property GREEN_THRESHOLD_MIN UNITS None
set_parameter_property GREEN_THRESHOLD_MIN ALLOWED_RANGES 0:17179869183
set_parameter_property GREEN_THRESHOLD_MIN AFFECTS_GENERATION false
set_parameter_property GREEN_THRESHOLD_MIN HDL_PARAMETER true
add_parameter GREEN_THRESHOLD_MAX STD_LOGIC_VECTOR 599785019
set_parameter_property GREEN_THRESHOLD_MAX DEFAULT_VALUE 599785019
set_parameter_property GREEN_THRESHOLD_MAX DISPLAY_NAME GREEN_THRESHOLD_MAX
set_parameter_property GREEN_THRESHOLD_MAX TYPE STD_LOGIC_VECTOR
set_parameter_property GREEN_THRESHOLD_MAX UNITS None
set_parameter_property GREEN_THRESHOLD_MAX ALLOWED_RANGES 0:17179869183
set_parameter_property GREEN_THRESHOLD_MAX AFFECTS_GENERATION false
set_parameter_property GREEN_THRESHOLD_MAX HDL_PARAMETER true
add_parameter BLUE_THRESHOLD_MIN STD_LOGIC_VECTOR 212
set_parameter_property BLUE_THRESHOLD_MIN DEFAULT_VALUE 212
set_parameter_property BLUE_THRESHOLD_MIN DISPLAY_NAME BLUE_THRESHOLD_MIN
set_parameter_property BLUE_THRESHOLD_MIN TYPE STD_LOGIC_VECTOR
set_parameter_property BLUE_THRESHOLD_MIN UNITS None
set_parameter_property BLUE_THRESHOLD_MIN ALLOWED_RANGES 0:17179869183
set_parameter_property BLUE_THRESHOLD_MIN AFFECTS_GENERATION false
set_parameter_property BLUE_THRESHOLD_MIN HDL_PARAMETER true
add_parameter BLUE_THRESHOLD_MAX STD_LOGIC_VECTOR 577281023
set_parameter_property BLUE_THRESHOLD_MAX DEFAULT_VALUE 577281023
set_parameter_property BLUE_THRESHOLD_MAX DISPLAY_NAME BLUE_THRESHOLD_MAX
set_parameter_property BLUE_THRESHOLD_MAX TYPE STD_LOGIC_VECTOR
set_parameter_property BLUE_THRESHOLD_MAX UNITS None
set_parameter_property BLUE_THRESHOLD_MAX ALLOWED_RANGES 0:17179869183
set_parameter_property BLUE_THRESHOLD_MAX AFFECTS_GENERATION false
set_parameter_property BLUE_THRESHOLD_MAX HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock csi_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset csi_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset clock_reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_address address Input 8
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point export
# | 
add_interface export conduit end

set_interface_property export ENABLED true

add_interface_port export avs_export_red_threshold_min export Output 32
add_interface_port export avs_export_red_threshold_max export Output 32
add_interface_port export avs_export_green_threshold_min export Output 32
add_interface_port export avs_export_green_threshold_max export Output 32
add_interface_port export avs_export_blue_threshold_min export Output 32
add_interface_port export avs_export_blue_threshold_max export Output 32
# | 
# +-----------------------------------
