# TCL File Generated by Component Editor 10.1sp1
# Tue Sep 20 13:27:39 CEST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalon_locator "Locator" v7.2
# | null 2011.09.20.13:27:39
# | 
# | 
# | C:/Users/Jorge/workspace/VideoSensor/NiosSystem/avalon_locator/hdl/avalon_locator.v
# | 
# |    ./hdl/avalon_locator.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module avalon_locator
# | 
set_module_property NAME avalon_locator
set_module_property VERSION 7.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME Locator
set_module_property TOP_LEVEL_HDL_FILE hdl/avalon_locator.v
set_module_property TOP_LEVEL_HDL_MODULE avalon_locator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/avalon_locator.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter X STD_LOGIC_VECTOR 0
set_parameter_property X DEFAULT_VALUE 0
set_parameter_property X DISPLAY_NAME X
set_parameter_property X TYPE STD_LOGIC_VECTOR
set_parameter_property X UNITS None
set_parameter_property X ALLOWED_RANGES 0:16383
set_parameter_property X AFFECTS_GENERATION false
set_parameter_property X HDL_PARAMETER true
add_parameter Y STD_LOGIC_VECTOR 0
set_parameter_property Y DEFAULT_VALUE 0
set_parameter_property Y DISPLAY_NAME Y
set_parameter_property Y TYPE STD_LOGIC_VECTOR
set_parameter_property Y UNITS None
set_parameter_property Y ALLOWED_RANGES 0:16383
set_parameter_property Y AFFECTS_GENERATION false
set_parameter_property Y HDL_PARAMETER true
add_parameter WIDTH STD_LOGIC_VECTOR 2592
set_parameter_property WIDTH DEFAULT_VALUE 2592
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE STD_LOGIC_VECTOR
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES 0:16383
set_parameter_property WIDTH AFFECTS_GENERATION false
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter HEIGHT STD_LOGIC_VECTOR 1944
set_parameter_property HEIGHT DEFAULT_VALUE 1944
set_parameter_property HEIGHT DISPLAY_NAME HEIGHT
set_parameter_property HEIGHT TYPE STD_LOGIC_VECTOR
set_parameter_property HEIGHT UNITS None
set_parameter_property HEIGHT ALLOWED_RANGES 0:16383
set_parameter_property HEIGHT AFFECTS_GENERATION false
set_parameter_property HEIGHT HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock csi_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset csi_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset clock_reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_address address Input 6
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point export
# | 
add_interface export conduit end

set_interface_property export ENABLED true

add_interface_port export avs_export_clock export Input 1
add_interface_port export avs_export_write export Input 1
add_interface_port export avs_export_pixel export Input 1
add_interface_port export avs_export_x export Input 12
add_interface_port export avs_export_y export Input 12
add_interface_port export avs_export_done export Input 1
add_interface_port export avs_export_width export Input 12
add_interface_port export avs_export_height export Input 12
# | 
# +-----------------------------------
